# Generated by Django 5.1.4 on 2025-05-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_guides', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlearningprogress',
            name='level',
            field=models.IntegerField(choices=[(1, '초급 - AdvancedGuide'), (2, '중급 - AdvancedGuide'), (3, '고급 - AdvancedGuide')]),
        ),
    ]
