# Generated by Django 3.2.25 on 2025-04-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_useractivation'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivation',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
