# Generated by Django 5.1.4 on 2025-01-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_stockportfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockportfolio',
            name='user',
        ),
        migrations.AddField(
            model_name='stockportfolio',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockportfolio',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
