# Generated by Django 3.2.25 on 2025-02-07 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_stockportfolio_user_stockportfolio_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockPortfolio',
        ),
    ]
