# Generated by Django 5.1.4 on 2025-05-02 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_passwordresetcode"),
        ("users", "0004_useractivation_code"),
    ]

    operations = []
