# Generated by Django 3.2.25 on 2025-05-02 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_passwordresetcode'),
        ('users', '0004_useractivation_code'),
    ]

    operations = [
    ]
