# Generated by Django 3.2.25 on 2025-02-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=1000000.0, max_digits=15),
        ),
    ]
