# Generated by Django 5.1.4 on 2025-05-11 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_userbalance"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserBalance",
        ),
    ]
