# Generated by Django 5.1.4 on 2025-08-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_passwordresettoken_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="has_completed_tutorial",
            field=models.BooleanField(default=False),
        ),
    ]
