# Generated by Django 5.1.4 on 2025-03-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0002_stocktrade"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocktrade",
            name="trade_type",
            field=models.CharField(
                choices=[("buy", "매수"), ("sell", "매도")],
                default="buy",
                max_length=10,
            ),
        ),
    ]
