# Generated by Django 5.1.4 on 2025-03-31 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0003_stocktrade_trade_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockportfolio",
            name="total_cost",
            field=models.IntegerField(default=0),
        ),
    ]
