# Generated by Django 5.1.4 on 2025-04-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0004_stockportfolio_total_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockportfolio",
            name="stock_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
