# Generated by Django 5.1.4 on 2025-08-18 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PushToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=512, unique=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("ANDROID", "ANDROID"),
                            ("IOS", "IOS"),
                            ("WEB", "WEB"),
                        ],
                        max_length=16,
                    ),
                ),
                ("device_id", models.CharField(blank=True, max_length=255, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("app_version", models.CharField(blank=True, max_length=64, null=True)),
                ("os_version", models.CharField(blank=True, max_length=64, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user"], name="push_tokens_user_id_471ac5_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="push_tokens_is_acti_071a24_idx"
                    ),
                    models.Index(
                        fields=["platform"], name="push_tokens_platfor_b55b54_idx"
                    ),
                ],
            },
        ),
    ]
