# Generated by Django 5.1.4 on 2025-08-18 05:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("push_tokens", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="pushtoken",
            unique_together={("user", "device_id")},
        ),
        migrations.AddIndex(
            model_name="pushtoken",
            index=models.Index(
                fields=["device_id"], name="push_tokens_device__921228_idx"
            ),
        ),
    ]
