# Generated by Django 5.1.4 on 2025-08-18 06:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("push_tokens", "0002_alter_pushtoken_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="pushtoken",
            name="push_tokens_user_id_471ac5_idx",
        ),
        migrations.RemoveIndex(
            model_name="pushtoken",
            name="push_tokens_is_acti_071a24_idx",
        ),
        migrations.RemoveIndex(
            model_name="pushtoken",
            name="push_tokens_platfor_b55b54_idx",
        ),
        migrations.RemoveIndex(
            model_name="pushtoken",
            name="push_tokens_device__921228_idx",
        ),
        migrations.AlterUniqueTogether(
            name="pushtoken",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="pushtoken",
            name="device_id",
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name="pushtoken",
            name="platform",
            field=models.CharField(
                choices=[("web", "web"), ("android", "android"), ("ios", "ios")],
                default="web",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="pushtoken",
            name="token",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name="pushtoken",
            index=models.Index(
                fields=["user", "platform"], name="push_tokens_user_id_f3c258_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="pushtoken",
            name="app_version",
        ),
        migrations.RemoveField(
            model_name="pushtoken",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="pushtoken",
            name="last_seen_at",
        ),
        migrations.RemoveField(
            model_name="pushtoken",
            name="os_version",
        ),
        migrations.RemoveField(
            model_name="pushtoken",
            name="revoked_at",
        ),
    ]
