# Generated by Django 5.1.4 on 2025-08-29 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "push_tokens",
            "0003_remove_pushtoken_push_tokens_user_id_471ac5_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="pushtoken",
            name="push_tokens_user_id_f3c258_idx",
        ),
        migrations.AddField(
            model_name="pushtoken",
            name="app_version",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="pushtoken",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="pushtoken",
            name="os_version",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="pushtoken",
            name="revoked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="pushtoken",
            index=models.Index(
                fields=["is_active"], name="push_tokens_is_acti_071a24_idx"
            ),
        ),
    ]
