# Generated by Django 5.1.4 on 2025-03-23 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chatbotresponse',
            table='chatbot_response',
        ),
    ]
