# Generated by Django 5.1.4 on 2025-03-23 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_chatbotresponse_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chatbotresponse',
            table=None,
        ),
    ]
