# Generated by Django 3.2.25 on 2025-02-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=350)),
                ('token_type', models.CharField(max_length=20)),
                ('expires_in', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('is_expired', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_key', models.CharField(max_length=286)),
            ],
        ),
    ]
