# Generated by Django 5.1.4 on 2025-03-24 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBTI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentmbti',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
