# Generated by Django 5.1.4 on 2025-03-24 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MBTI', '0002_alter_investmentmbti_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentmbti',
            name='created_at',
        ),
    ]
