# Generated by Django 5.1.4 on 2025-03-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBTI', '0003_remove_investmentmbti_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbtiquestion',
            name='type_a',
            field=models.CharField(default='S', max_length=1),
        ),
        migrations.AddField(
            model_name='mbtiquestion',
            name='type_b',
            field=models.CharField(default='R', max_length=1),
        ),
        migrations.AlterField(
            model_name='mbtiquestion',
            name='related_trait',
            field=models.CharField(max_length=3),
        ),
    ]
